name: aureum_sentinel_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - pyarrow
  - requests
  - pip
  - pip:
    - yfinance
    - fastparquet
    - google-generativeai
